In this repository, we will perform different tensor operations as well as use [GradientTape](https://www.tensorflow.org/api_docs/python/tf/GradientTape). These are important building blocks for building a complete custom model.

In [ ]:
import tensorflow as tf
import numpy as np

 - [tf.constant]((https://www.tensorflow.org/api_docs/python/tf/constant))

Creates a constant tensor from a tensor-like object. 

In [ ]:
# Convert NumPy array to Tensor using `tf.constant`
def tf_constant(array):
    """
    Args:
        array (numpy.ndarray): tensor-like array.

    Returns:
        tensorflow.python.framework.ops.EagerTensor: tensor.
    """
    tf_constant_array = tf.constant(array)
    return tf_constant_array

In [ ]:
tmp_array = np.arange(1,15)
x = tf_constant(tmp_array)
x

<tf.Tensor: shape=(14,), dtype=int64, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])>

- [tf.square](https://www.tensorflow.org/api_docs/python/tf/math/square)

Computes the square of a tensor element-wise.

In [ ]:
# Square the input tensor
def tf_square(array):
    """
    Args:
        array (numpy.ndarray): tensor-like array.

    Returns:
        EagerTensor: tensor.
    """
    # make sure it's a tensor
    array = tf.constant(array)
    tf_squared_array = array **2
    return tf_squared_array 

In [ ]:
tmp_array = tf.constant(np.arange(1, 15))
x = tf_square(tmp_array)
x

<tf.Tensor: shape=(14,), dtype=int64, numpy=
array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196])>

- [tf.reshape](https://www.tensorflow.org/api_docs/python/tf/reshape)

Reshapes a tensor.

In [ ]:
# Reshape tensor into the given shape parameter
def tf_reshape(array, shape):
    """
    Args:
        array (EagerTensor): tensor to reshape.
        shape (tuple): desired shape.

    Returns:
        EagerTensor: reshaped tensor.
    """
    # make sure it's a tensor
    array = tf.constant(array)
    tf_reshaped_array = tf.reshape(array,shape)
    return tf_reshaped_array

In [ ]:
# Check your function
tmp_array = np.array([10,20,30,40,50,60,70,80,90])
# Check that your function reshapes a vector into a matrix
x = tf_reshape(tmp_array, (3, 3))
x

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])>

 - [tf.cast](https://www.tensorflow.org/api_docs/python/tf/cast)

Casts a tensor to a new type.

In [ ]:
# Cast tensor into the given dtype parameter
def tf_cast(array, dtype):
    """
    Args:
        array (EagerTensor): tensor to be casted.
        dtype (tensorflow.python.framework.dtypes.DType): desired new type. (Should be a TF dtype!)

    Returns:
        EagerTensor: casted tensor.
    """
    # make sure it's a tensor
    array = tf.constant(array)
    tf_cast_array = tf.cast(array,dtype)
    return tf_cast_array

In [ ]:
# Check your function
tmp_array = [10,20,30,40]
x = tf_cast(tmp_array, tf.float32)
x

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([10., 20., 30., 40.], dtype=float32)>

 - [tf.multiply](https://www.tensorflow.org/api_docs/python/tf/multiply)

Returns an element-wise x * y.

In [ ]:
# Multiply tensor1 and tensor2
def tf_multiply(tensor1, tensor2):
    """
    Args:
        tensor1 (EagerTensor): a tensor.
        tensor2 (EagerTensor): another tensor.

    Returns:
        EagerTensor: resulting tensor.
    """
    # make sure these are tensors
    tensor1 = tf.constant(tensor1)
    tensor2 = tf.constant(tensor2)
    product = tf.multiply(tensor1,tensor2)
    return product

In [ ]:
# Check your function
tmp_1 = tf.constant(np.array([[1,2],[3,4]]))
tmp_2 = tf.constant(np.array(2))
result = tf_multiply(tmp_1, tmp_2)
result

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[2, 4],
       [6, 8]])>

 - [tf.add](https://www.tensorflow.org/api_docs/python/tf/add)

Returns x + y element-wise.

In [ ]:
# Add tensor1 and tensor2
def tf_add(tensor1, tensor2):
    """
    Args:
        tensor1 (EagerTensor): a tensor.
        tensor2 (EagerTensor): another tensor.

    Returns:
        EagerTensor: resulting tensor.
    """
    tensor1 = tf.constant(tensor1)
    tensor2 = tf.constant(tensor2)
    total = tf.add(tensor1,tensor2)
    return total

In [ ]:
# Check your function
tmp_1 = tf.constant(np.array([1, 2, 3]))
tmp_2 = tf.constant(np.array([4, 5, 6]))
tf_add(tmp_1, tmp_2)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([5, 7, 9])>

 - 
 [Gradient Tape](https://www.tensorflow.org/api_docs/python/tf/GradientTape)
 This is important for creating a custom gradient decent.

In [ ]:
def tf_gradient_tape(x):
    """
    Args:
        x (EagerTensor): a tensor.

    Returns:
        EagerTensor: Derivative of z with respect to the input tensor x.
    """
    with tf.GradientTape() as t:
        
    # No gradients will be available if it isnnot being watched.
        # Record the actions performed on tensor x with `watch`
        t.watch(x)   

        # Define a polynomial of form 3x^3 - 2x^2 + x
        y = ((3*x)**3)-((2*x)**2) + x

        # Obtain the sum of the elements in variable y
        z = tf.reduce_sum(y)
  
    # Get the derivative of z with respect to the original input tensor x
    dz_dx = t.gradient(z,x)
    
    return dz_dx

In [ ]:
tmp_x = tf.constant(2.0)
dz_dx = tf_gradient_tape(tmp_x)
result = dz_dx.numpy()
result

309.0